### ISSUE TITLE
npm install failed at Windows machines

### ISSUE THREAD

**Issue by benmb1984** [csstools/system-font-css#10]
Hi Jonathan,

I get an error during the installation of your package. It seems like PowerShell on Windows is using cmd.exe during builds. In your script I see some `cp` commands. I hope you have some time for this.

More info: [https://github.com/ReactiveX/rxjs/issues/1601](https://github.com/ReactiveX/rxjs/issues/1601)

Kind regards,
Ben

**Comment by zachleat** [comment]
Wasn’t this fixed in #8?

**Comment by benmb1984** [comment]
No, I have test it on multiple Windows machines. Same error everywhere.

![image](https://user-images.githubusercontent.com/5637670/33762917-bea5dbaa-dc0e-11e7-85de-32747a72759b.png)

**Comment by zachleat** [comment]
Why is it using `cp` there? #8 changed it to use `cpr`. Do we need to tag another release or something to update?

**Comment by benmb1984** [comment]
cpr is used in the latest release I have tested. Maybe cpr itself (or node.js) is using the `copy` command. 

Maybe the most easy solution is don't copy the file during install. Provide both files already in your repository.

**Comment by zachleat** [comment]
What’s in your `package.json` for the install script? Can you run `npm run install`?

**Comment by zachleat** [comment]
I just checked and yes, the `cpr` version was unreleased to `npm`. Try again with 2.0.2 please!

**Comment by benmb1984** [comment]
Hi Zachleat,
Problem solved. It works now with classic CMD and PowerShell.
Many thanks!
